//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.11.30 at 03:01:31 PM IST 
//

package com.punj.app.ecommerce.tally.export.voucher;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for anonymous complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="HEADER">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="VERSION" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="TALLYREQUEST" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="TYPE" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="ID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="STATUS" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="BODY">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="DESC">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="STATICVARIABLES">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="IMPORTDUPS" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="DATA">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="IMPORTRESULT">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="CREATED" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                                       &lt;element name="ALTERED" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                                       &lt;element name="LASTVCHID" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                                       &lt;element name="LASTMID" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                                       &lt;element name="COMBINED" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                                       &lt;element name="IGNORED" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                                       &lt;element name="ERRORS" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                             &lt;element name="TALLYMESSAGE">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="VOUCHER" maxOccurs="unbounded">
 *                                         &lt;complexType>
 *                                           &lt;complexContent>
 *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                               &lt;sequence>
 *                                                 &lt;element name="DATE" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                                                 &lt;element name="NARRATION" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                                 &lt;element name="VOUCHERTYPENAME" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                                 &lt;element name="VOUCHERNUMBER" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                                                 &lt;element name="ALLLEDGERENTRIES.LIST" maxOccurs="unbounded">
 *                                                   &lt;complexType>
 *                                                     &lt;complexContent>
 *                                                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                                         &lt;sequence>
 *                                                           &lt;element name="LEDGERNAME" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                                           &lt;element name="ISDEEMEDPOSITIVE" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                                           &lt;element name="AMOUNT" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                                                         &lt;/sequence>
 *                                                       &lt;/restriction>
 *                                                     &lt;/complexContent>
 *                                                   &lt;/complexType>
 *                                                 &lt;/element>
 *                                               &lt;/sequence>
 *                                             &lt;/restriction>
 *                                           &lt;/complexContent>
 *                                         &lt;/complexType>
 *                                       &lt;/element>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = { "header", "body" })
@XmlRootElement(name = "ENVELOPE")
public class ENVELOPE {

	@XmlElement(name = "HEADER", required = true)
	protected ENVELOPE.HEADER header;
	@XmlElement(name = "BODY", required = true)
	protected ENVELOPE.BODY body;

	/**
	 * Gets the value of the header property.
	 * 
	 * @return possible object is {@link ENVELOPE.HEADER }
	 * 
	 */
	public ENVELOPE.HEADER getHEADER() {
		return header;
	}

	/**
	 * Sets the value of the header property.
	 * 
	 * @param value
	 *            allowed object is {@link ENVELOPE.HEADER }
	 * 
	 */
	public void setHEADER(ENVELOPE.HEADER value) {
		this.header = value;
	}

	/**
	 * Gets the value of the body property.
	 * 
	 * @return possible object is {@link ENVELOPE.BODY }
	 * 
	 */
	public ENVELOPE.BODY getBODY() {
		return body;
	}

	/**
	 * Sets the value of the body property.
	 * 
	 * @param value
	 *            allowed object is {@link ENVELOPE.BODY }
	 * 
	 */
	public void setBODY(ENVELOPE.BODY value) {
		this.body = value;
	}

	/**
	 * <p>
	 * Java class for anonymous complex type.
	 * 
	 * <p>
	 * The following schema fragment specifies the expected content contained within this class.
	 * 
	 * <pre>
	 * &lt;complexType>
	 *   &lt;complexContent>
	 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	 *       &lt;sequence>
	 *         &lt;element name="DESC">
	 *           &lt;complexType>
	 *             &lt;complexContent>
	 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	 *                 &lt;sequence>
	 *                   &lt;element name="STATICVARIABLES">
	 *                     &lt;complexType>
	 *                       &lt;complexContent>
	 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	 *                           &lt;sequence>
	 *                             &lt;element name="IMPORTDUPS" type="{http://www.w3.org/2001/XMLSchema}string"/>
	 *                           &lt;/sequence>
	 *                         &lt;/restriction>
	 *                       &lt;/complexContent>
	 *                     &lt;/complexType>
	 *                   &lt;/element>
	 *                 &lt;/sequence>
	 *               &lt;/restriction>
	 *             &lt;/complexContent>
	 *           &lt;/complexType>
	 *         &lt;/element>
	 *         &lt;element name="DATA">
	 *           &lt;complexType>
	 *             &lt;complexContent>
	 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	 *                 &lt;sequence>
	 *                   &lt;element name="IMPORTRESULT">
	 *                     &lt;complexType>
	 *                       &lt;complexContent>
	 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	 *                           &lt;sequence>
	 *                             &lt;element name="CREATED" type="{http://www.w3.org/2001/XMLSchema}int"/>
	 *                             &lt;element name="ALTERED" type="{http://www.w3.org/2001/XMLSchema}int"/>
	 *                             &lt;element name="LASTVCHID" type="{http://www.w3.org/2001/XMLSchema}int"/>
	 *                             &lt;element name="LASTMID" type="{http://www.w3.org/2001/XMLSchema}int"/>
	 *                             &lt;element name="COMBINED" type="{http://www.w3.org/2001/XMLSchema}int"/>
	 *                             &lt;element name="IGNORED" type="{http://www.w3.org/2001/XMLSchema}int"/>
	 *                             &lt;element name="ERRORS" type="{http://www.w3.org/2001/XMLSchema}int"/>
	 *                           &lt;/sequence>
	 *                         &lt;/restriction>
	 *                       &lt;/complexContent>
	 *                     &lt;/complexType>
	 *                   &lt;/element>
	 *                   &lt;element name="TALLYMESSAGE">
	 *                     &lt;complexType>
	 *                       &lt;complexContent>
	 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	 *                           &lt;sequence>
	 *                             &lt;element name="VOUCHER" maxOccurs="unbounded">
	 *                               &lt;complexType>
	 *                                 &lt;complexContent>
	 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	 *                                     &lt;sequence>
	 *                                       &lt;element name="DATE" type="{http://www.w3.org/2001/XMLSchema}int"/>
	 *                                       &lt;element name="NARRATION" type="{http://www.w3.org/2001/XMLSchema}string"/>
	 *                                       &lt;element name="VOUCHERTYPENAME" type="{http://www.w3.org/2001/XMLSchema}string"/>
	 *                                       &lt;element name="VOUCHERNUMBER" type="{http://www.w3.org/2001/XMLSchema}int"/>
	 *                                       &lt;element name="ALLLEDGERENTRIES.LIST" maxOccurs="unbounded">
	 *                                         &lt;complexType>
	 *                                           &lt;complexContent>
	 *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	 *                                               &lt;sequence>
	 *                                                 &lt;element name="LEDGERNAME" type="{http://www.w3.org/2001/XMLSchema}string"/>
	 *                                                 &lt;element name="ISDEEMEDPOSITIVE" type="{http://www.w3.org/2001/XMLSchema}string"/>
	 *                                                 &lt;element name="AMOUNT" type="{http://www.w3.org/2001/XMLSchema}int"/>
	 *                                               &lt;/sequence>
	 *                                             &lt;/restriction>
	 *                                           &lt;/complexContent>
	 *                                         &lt;/complexType>
	 *                                       &lt;/element>
	 *                                     &lt;/sequence>
	 *                                   &lt;/restriction>
	 *                                 &lt;/complexContent>
	 *                               &lt;/complexType>
	 *                             &lt;/element>
	 *                           &lt;/sequence>
	 *                         &lt;/restriction>
	 *                       &lt;/complexContent>
	 *                     &lt;/complexType>
	 *                   &lt;/element>
	 *                 &lt;/sequence>
	 *               &lt;/restriction>
	 *             &lt;/complexContent>
	 *           &lt;/complexType>
	 *         &lt;/element>
	 *       &lt;/sequence>
	 *     &lt;/restriction>
	 *   &lt;/complexContent>
	 * &lt;/complexType>
	 * </pre>
	 * 
	 * 
	 */
	@XmlAccessorType(XmlAccessType.FIELD)
	@XmlType(name = "", propOrder = { "desc", "data" })
	public static class BODY {

		@XmlElement(name = "DESC", required = true)
		protected ENVELOPE.BODY.DESC desc;
		@XmlElement(name = "DATA", required = true)
		protected ENVELOPE.BODY.DATA data;

		/**
		 * Gets the value of the desc property.
		 * 
		 * @return possible object is {@link ENVELOPE.BODY.DESC }
		 * 
		 */
		public ENVELOPE.BODY.DESC getDESC() {
			return desc;
		}

		/**
		 * Sets the value of the desc property.
		 * 
		 * @param value
		 *            allowed object is {@link ENVELOPE.BODY.DESC }
		 * 
		 */
		public void setDESC(ENVELOPE.BODY.DESC value) {
			this.desc = value;
		}

		/**
		 * Gets the value of the data property.
		 * 
		 * @return possible object is {@link ENVELOPE.BODY.DATA }
		 * 
		 */
		public ENVELOPE.BODY.DATA getDATA() {
			return data;
		}

		/**
		 * Sets the value of the data property.
		 * 
		 * @param value
		 *            allowed object is {@link ENVELOPE.BODY.DATA }
		 * 
		 */
		public void setDATA(ENVELOPE.BODY.DATA value) {
			this.data = value;
		}

		/**
		 * <p>
		 * Java class for anonymous complex type.
		 * 
		 * <p>
		 * The following schema fragment specifies the expected content contained within this class.
		 * 
		 * <pre>
		 * &lt;complexType>
		 *   &lt;complexContent>
		 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
		 *       &lt;sequence>
		 *         &lt;element name="IMPORTRESULT">
		 *           &lt;complexType>
		 *             &lt;complexContent>
		 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
		 *                 &lt;sequence>
		 *                   &lt;element name="CREATED" type="{http://www.w3.org/2001/XMLSchema}int"/>
		 *                   &lt;element name="ALTERED" type="{http://www.w3.org/2001/XMLSchema}int"/>
		 *                   &lt;element name="LASTVCHID" type="{http://www.w3.org/2001/XMLSchema}int"/>
		 *                   &lt;element name="LASTMID" type="{http://www.w3.org/2001/XMLSchema}int"/>
		 *                   &lt;element name="COMBINED" type="{http://www.w3.org/2001/XMLSchema}int"/>
		 *                   &lt;element name="IGNORED" type="{http://www.w3.org/2001/XMLSchema}int"/>
		 *                   &lt;element name="ERRORS" type="{http://www.w3.org/2001/XMLSchema}int"/>
		 *                 &lt;/sequence>
		 *               &lt;/restriction>
		 *             &lt;/complexContent>
		 *           &lt;/complexType>
		 *         &lt;/element>
		 *         &lt;element name="TALLYMESSAGE">
		 *           &lt;complexType>
		 *             &lt;complexContent>
		 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
		 *                 &lt;sequence>
		 *                   &lt;element name="VOUCHER" maxOccurs="unbounded">
		 *                     &lt;complexType>
		 *                       &lt;complexContent>
		 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
		 *                           &lt;sequence>
		 *                             &lt;element name="DATE" type="{http://www.w3.org/2001/XMLSchema}int"/>
		 *                             &lt;element name="NARRATION" type="{http://www.w3.org/2001/XMLSchema}string"/>
		 *                             &lt;element name="VOUCHERTYPENAME" type="{http://www.w3.org/2001/XMLSchema}string"/>
		 *                             &lt;element name="VOUCHERNUMBER" type="{http://www.w3.org/2001/XMLSchema}int"/>
		 *                             &lt;element name="ALLLEDGERENTRIES.LIST" maxOccurs="unbounded">
		 *                               &lt;complexType>
		 *                                 &lt;complexContent>
		 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
		 *                                     &lt;sequence>
		 *                                       &lt;element name="LEDGERNAME" type="{http://www.w3.org/2001/XMLSchema}string"/>
		 *                                       &lt;element name="ISDEEMEDPOSITIVE" type="{http://www.w3.org/2001/XMLSchema}string"/>
		 *                                       &lt;element name="AMOUNT" type="{http://www.w3.org/2001/XMLSchema}int"/>
		 *                                     &lt;/sequence>
		 *                                   &lt;/restriction>
		 *                                 &lt;/complexContent>
		 *                               &lt;/complexType>
		 *                             &lt;/element>
		 *                           &lt;/sequence>
		 *                         &lt;/restriction>
		 *                       &lt;/complexContent>
		 *                     &lt;/complexType>
		 *                   &lt;/element>
		 *                 &lt;/sequence>
		 *               &lt;/restriction>
		 *             &lt;/complexContent>
		 *           &lt;/complexType>
		 *         &lt;/element>
		 *       &lt;/sequence>
		 *     &lt;/restriction>
		 *   &lt;/complexContent>
		 * &lt;/complexType>
		 * </pre>
		 * 
		 * 
		 */
		@XmlAccessorType(XmlAccessType.FIELD)
		@XmlType(name = "", propOrder = { "importresult", "tallymessage" })
		public static class DATA {

			@XmlElement(name = "IMPORTRESULT", required = true)
			protected ENVELOPE.BODY.DATA.IMPORTRESULT importresult;
			@XmlElement(name = "TALLYMESSAGE", required = true)
			protected ENVELOPE.BODY.DATA.TALLYMESSAGE tallymessage;

			/**
			 * Gets the value of the importresult property.
			 * 
			 * @return possible object is {@link ENVELOPE.BODY.DATA.IMPORTRESULT }
			 * 
			 */
			public ENVELOPE.BODY.DATA.IMPORTRESULT getIMPORTRESULT() {
				return importresult;
			}

			/**
			 * Sets the value of the importresult property.
			 * 
			 * @param value
			 *            allowed object is {@link ENVELOPE.BODY.DATA.IMPORTRESULT }
			 * 
			 */
			public void setIMPORTRESULT(ENVELOPE.BODY.DATA.IMPORTRESULT value) {
				this.importresult = value;
			}

			/**
			 * Gets the value of the tallymessage property.
			 * 
			 * @return possible object is {@link ENVELOPE.BODY.DATA.TALLYMESSAGE }
			 * 
			 */
			public ENVELOPE.BODY.DATA.TALLYMESSAGE getTALLYMESSAGE() {
				return tallymessage;
			}

			/**
			 * Sets the value of the tallymessage property.
			 * 
			 * @param value
			 *            allowed object is {@link ENVELOPE.BODY.DATA.TALLYMESSAGE }
			 * 
			 */
			public void setTALLYMESSAGE(ENVELOPE.BODY.DATA.TALLYMESSAGE value) {
				this.tallymessage = value;
			}

			/**
			 * <p>
			 * Java class for anonymous complex type.
			 * 
			 * <p>
			 * The following schema fragment specifies the expected content contained within this class.
			 * 
			 * <pre>
			 * &lt;complexType>
			 *   &lt;complexContent>
			 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
			 *       &lt;sequence>
			 *         &lt;element name="CREATED" type="{http://www.w3.org/2001/XMLSchema}int"/>
			 *         &lt;element name="ALTERED" type="{http://www.w3.org/2001/XMLSchema}int"/>
			 *         &lt;element name="LASTVCHID" type="{http://www.w3.org/2001/XMLSchema}int"/>
			 *         &lt;element name="LASTMID" type="{http://www.w3.org/2001/XMLSchema}int"/>
			 *         &lt;element name="COMBINED" type="{http://www.w3.org/2001/XMLSchema}int"/>
			 *         &lt;element name="IGNORED" type="{http://www.w3.org/2001/XMLSchema}int"/>
			 *         &lt;element name="ERRORS" type="{http://www.w3.org/2001/XMLSchema}int"/>
			 *       &lt;/sequence>
			 *     &lt;/restriction>
			 *   &lt;/complexContent>
			 * &lt;/complexType>
			 * </pre>
			 * 
			 * 
			 */
			@XmlAccessorType(XmlAccessType.FIELD)
			@XmlType(name = "", propOrder = { "created", "altered", "lastvchid", "lastmid", "combined", "ignored", "errors" })
			public static class IMPORTRESULT {

				@XmlElement(name = "CREATED")
				protected int created;
				@XmlElement(name = "ALTERED")
				protected int altered;
				@XmlElement(name = "LASTVCHID")
				protected int lastvchid;
				@XmlElement(name = "LASTMID")
				protected int lastmid;
				@XmlElement(name = "COMBINED")
				protected int combined;
				@XmlElement(name = "IGNORED")
				protected int ignored;
				@XmlElement(name = "ERRORS")
				protected int errors;

				/**
				 * Gets the value of the created property.
				 * 
				 */
				public int getCREATED() {
					return created;
				}

				/**
				 * Sets the value of the created property.
				 * 
				 */
				public void setCREATED(int value) {
					this.created = value;
				}

				/**
				 * Gets the value of the altered property.
				 * 
				 */
				public int getALTERED() {
					return altered;
				}

				/**
				 * Sets the value of the altered property.
				 * 
				 */
				public void setALTERED(int value) {
					this.altered = value;
				}

				/**
				 * Gets the value of the lastvchid property.
				 * 
				 */
				public int getLASTVCHID() {
					return lastvchid;
				}

				/**
				 * Sets the value of the lastvchid property.
				 * 
				 */
				public void setLASTVCHID(int value) {
					this.lastvchid = value;
				}

				/**
				 * Gets the value of the lastmid property.
				 * 
				 */
				public int getLASTMID() {
					return lastmid;
				}

				/**
				 * Sets the value of the lastmid property.
				 * 
				 */
				public void setLASTMID(int value) {
					this.lastmid = value;
				}

				/**
				 * Gets the value of the combined property.
				 * 
				 */
				public int getCOMBINED() {
					return combined;
				}

				/**
				 * Sets the value of the combined property.
				 * 
				 */
				public void setCOMBINED(int value) {
					this.combined = value;
				}

				/**
				 * Gets the value of the ignored property.
				 * 
				 */
				public int getIGNORED() {
					return ignored;
				}

				/**
				 * Sets the value of the ignored property.
				 * 
				 */
				public void setIGNORED(int value) {
					this.ignored = value;
				}

				/**
				 * Gets the value of the errors property.
				 * 
				 */
				public int getERRORS() {
					return errors;
				}

				/**
				 * Sets the value of the errors property.
				 * 
				 */
				public void setERRORS(int value) {
					this.errors = value;
				}

			}

			/**
			 * <p>
			 * Java class for anonymous complex type.
			 * 
			 * <p>
			 * The following schema fragment specifies the expected content contained within this class.
			 * 
			 * <pre>
			 * &lt;complexType>
			 *   &lt;complexContent>
			 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
			 *       &lt;sequence>
			 *         &lt;element name="VOUCHER" maxOccurs="unbounded">
			 *           &lt;complexType>
			 *             &lt;complexContent>
			 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
			 *                 &lt;sequence>
			 *                   &lt;element name="DATE" type="{http://www.w3.org/2001/XMLSchema}int"/>
			 *                   &lt;element name="NARRATION" type="{http://www.w3.org/2001/XMLSchema}string"/>
			 *                   &lt;element name="VOUCHERTYPENAME" type="{http://www.w3.org/2001/XMLSchema}string"/>
			 *                   &lt;element name="VOUCHERNUMBER" type="{http://www.w3.org/2001/XMLSchema}int"/>
			 *                   &lt;element name="ALLLEDGERENTRIES.LIST" maxOccurs="unbounded">
			 *                     &lt;complexType>
			 *                       &lt;complexContent>
			 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
			 *                           &lt;sequence>
			 *                             &lt;element name="LEDGERNAME" type="{http://www.w3.org/2001/XMLSchema}string"/>
			 *                             &lt;element name="ISDEEMEDPOSITIVE" type="{http://www.w3.org/2001/XMLSchema}string"/>
			 *                             &lt;element name="AMOUNT" type="{http://www.w3.org/2001/XMLSchema}int"/>
			 *                           &lt;/sequence>
			 *                         &lt;/restriction>
			 *                       &lt;/complexContent>
			 *                     &lt;/complexType>
			 *                   &lt;/element>
			 *                 &lt;/sequence>
			 *               &lt;/restriction>
			 *             &lt;/complexContent>
			 *           &lt;/complexType>
			 *         &lt;/element>
			 *       &lt;/sequence>
			 *     &lt;/restriction>
			 *   &lt;/complexContent>
			 * &lt;/complexType>
			 * </pre>
			 * 
			 * 
			 */
			@XmlAccessorType(XmlAccessType.FIELD)
			@XmlType(name = "", propOrder = { "voucher" })
			public static class TALLYMESSAGE {

				@XmlElement(name = "VOUCHER", required = true)
				protected List<ENVELOPE.BODY.DATA.TALLYMESSAGE.VOUCHER> voucher;

				/**
				 * Gets the value of the voucher property.
				 * 
				 * <p>
				 * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you make to the returned list will be present inside
				 * the JAXB object. This is why there is not a <CODE>set</CODE> method for the voucher property.
				 * 
				 * <p>
				 * For example, to add a new item, do as follows:
				 * 
				 * <pre>
				 * getVOUCHER().add(newItem);
				 * </pre>
				 * 
				 * 
				 * <p>
				 * Objects of the following type(s) are allowed in the list {@link ENVELOPE.BODY.DATA.TALLYMESSAGE.VOUCHER }
				 * 
				 * 
				 */
				public List<ENVELOPE.BODY.DATA.TALLYMESSAGE.VOUCHER> getVOUCHER() {
					if (voucher == null) {
						voucher = new ArrayList<ENVELOPE.BODY.DATA.TALLYMESSAGE.VOUCHER>();
					}
					return this.voucher;
				}

				/**
				 * <p>
				 * Java class for anonymous complex type.
				 * 
				 * <p>
				 * The following schema fragment specifies the expected content contained within this class.
				 * 
				 * <pre>
				 * &lt;complexType>
				 *   &lt;complexContent>
				 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
				 *       &lt;sequence>
				 *         &lt;element name="DATE" type="{http://www.w3.org/2001/XMLSchema}int"/>
				 *         &lt;element name="NARRATION" type="{http://www.w3.org/2001/XMLSchema}string"/>
				 *         &lt;element name="VOUCHERTYPENAME" type="{http://www.w3.org/2001/XMLSchema}string"/>
				 *         &lt;element name="VOUCHERNUMBER" type="{http://www.w3.org/2001/XMLSchema}int"/>
				 *         &lt;element name="ALLLEDGERENTRIES.LIST" maxOccurs="unbounded">
				 *           &lt;complexType>
				 *             &lt;complexContent>
				 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
				 *                 &lt;sequence>
				 *                   &lt;element name="LEDGERNAME" type="{http://www.w3.org/2001/XMLSchema}string"/>
				 *                   &lt;element name="ISDEEMEDPOSITIVE" type="{http://www.w3.org/2001/XMLSchema}string"/>
				 *                   &lt;element name="AMOUNT" type="{http://www.w3.org/2001/XMLSchema}int"/>
				 *                 &lt;/sequence>
				 *               &lt;/restriction>
				 *             &lt;/complexContent>
				 *           &lt;/complexType>
				 *         &lt;/element>
				 *       &lt;/sequence>
				 *     &lt;/restriction>
				 *   &lt;/complexContent>
				 * &lt;/complexType>
				 * </pre>
				 * 
				 * 
				 */
				@XmlAccessorType(XmlAccessType.FIELD)
				@XmlType(name = "", propOrder = { "date", "narration", "vouchertypename", "vouchernumber", "allledgerentrieslist" })
				public static class VOUCHER {

					@XmlElement(name = "DATE")
					protected String date;
					@XmlElement(name = "NARRATION", required = true)
					protected String narration;
					@XmlElement(name = "VOUCHERTYPENAME", required = true)
					protected String vouchertypename;
					@XmlElement(name = "VOUCHERNUMBER")
					protected String vouchernumber;
					@XmlElement(name = "ALLLEDGERENTRIES.LIST", required = true)
					protected List<ENVELOPE.BODY.DATA.TALLYMESSAGE.VOUCHER.ALLLEDGERENTRIESLIST> allledgerentrieslist;

					/**
					 * Gets the value of the date property.
					 * 
					 */
					public String getDATE() {
						return date;
					}

					/**
					 * Sets the value of the date property.
					 * 
					 */
					public void setDATE(String value) {
						this.date = value;
					}

					/**
					 * Gets the value of the narration property.
					 * 
					 * @return possible object is {@link String }
					 * 
					 */
					public String getNARRATION() {
						return narration;
					}

					/**
					 * Sets the value of the narration property.
					 * 
					 * @param value
					 *            allowed object is {@link String }
					 * 
					 */
					public void setNARRATION(String value) {
						this.narration = value;
					}

					/**
					 * Gets the value of the vouchertypename property.
					 * 
					 * @return possible object is {@link String }
					 * 
					 */
					public String getVOUCHERTYPENAME() {
						return vouchertypename;
					}

					/**
					 * Sets the value of the vouchertypename property.
					 * 
					 * @param value
					 *            allowed object is {@link String }
					 * 
					 */
					public void setVOUCHERTYPENAME(String value) {
						this.vouchertypename = value;
					}

					/**
					 * Gets the value of the vouchernumber property.
					 * 
					 */
					public String getVOUCHERNUMBER() {
						return vouchernumber;
					}

					/**
					 * Sets the value of the vouchernumber property.
					 * 
					 */
					public void setVOUCHERNUMBER(String value) {
						this.vouchernumber = value;
					}

					/**
					 * Gets the value of the allledgerentrieslist property.
					 * 
					 * <p>
					 * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you make to the returned list will be present inside
					 * the JAXB object. This is why there is not a <CODE>set</CODE> method for the allledgerentrieslist property.
					 * 
					 * <p>
					 * For example, to add a new item, do as follows:
					 * 
					 * <pre>
					 * getALLLEDGERENTRIESLIST().add(newItem);
					 * </pre>
					 * 
					 * 
					 * <p>
					 * Objects of the following type(s) are allowed in the list {@link ENVELOPE.BODY.DATA.TALLYMESSAGE.VOUCHER.ALLLEDGERENTRIESLIST }
					 * 
					 * 
					 */
					public List<ENVELOPE.BODY.DATA.TALLYMESSAGE.VOUCHER.ALLLEDGERENTRIESLIST> getALLLEDGERENTRIESLIST() {
						if (allledgerentrieslist == null) {
							allledgerentrieslist = new ArrayList<ENVELOPE.BODY.DATA.TALLYMESSAGE.VOUCHER.ALLLEDGERENTRIESLIST>();
						}
						return this.allledgerentrieslist;
					}

					/**
					 * <p>
					 * Java class for anonymous complex type.
					 * 
					 * <p>
					 * The following schema fragment specifies the expected content contained within this class.
					 * 
					 * <pre>
					 * &lt;complexType>
					 *   &lt;complexContent>
					 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
					 *       &lt;sequence>
					 *         &lt;element name="LEDGERNAME" type="{http://www.w3.org/2001/XMLSchema}string"/>
					 *         &lt;element name="ISDEEMEDPOSITIVE" type="{http://www.w3.org/2001/XMLSchema}string"/>
					 *         &lt;element name="AMOUNT" type="{http://www.w3.org/2001/XMLSchema}int"/>
					 *       &lt;/sequence>
					 *     &lt;/restriction>
					 *   &lt;/complexContent>
					 * &lt;/complexType>
					 * </pre>
					 * 
					 * 
					 */
					@XmlAccessorType(XmlAccessType.FIELD)
					@XmlType(name = "", propOrder = { "ledgername", "isdeemedpositive", "amount" })
					public static class ALLLEDGERENTRIESLIST {

						@XmlElement(name = "LEDGERNAME", required = true)
						protected String ledgername;
						@XmlElement(name = "ISDEEMEDPOSITIVE", required = true)
						protected String isdeemedpositive;
						@XmlElement(name = "AMOUNT")
						protected BigDecimal amount;

						/**
						 * Gets the value of the ledgername property.
						 * 
						 * @return possible object is {@link String }
						 * 
						 */
						public String getLEDGERNAME() {
							return ledgername;
						}

						/**
						 * Sets the value of the ledgername property.
						 * 
						 * @param value
						 *            allowed object is {@link String }
						 * 
						 */
						public void setLEDGERNAME(String value) {
							this.ledgername = value;
						}

						/**
						 * Gets the value of the isdeemedpositive property.
						 * 
						 * @return possible object is {@link String }
						 * 
						 */
						public String getISDEEMEDPOSITIVE() {
							return isdeemedpositive;
						}

						/**
						 * Sets the value of the isdeemedpositive property.
						 * 
						 * @param value
						 *            allowed object is {@link String }
						 * 
						 */
						public void setISDEEMEDPOSITIVE(String value) {
							this.isdeemedpositive = value;
						}

						/**
						 * Gets the value of the amount property.
						 * 
						 */
						public BigDecimal getAMOUNT() {
							return amount;
						}

						/**
						 * Sets the value of the amount property.
						 * 
						 */
						public void setAMOUNT(BigDecimal value) {
							this.amount = value;
						}

					}

				}

			}

		}

		/**
		 * <p>
		 * Java class for anonymous complex type.
		 * 
		 * <p>
		 * The following schema fragment specifies the expected content contained within this class.
		 * 
		 * <pre>
		 * &lt;complexType>
		 *   &lt;complexContent>
		 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
		 *       &lt;sequence>
		 *         &lt;element name="STATICVARIABLES">
		 *           &lt;complexType>
		 *             &lt;complexContent>
		 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
		 *                 &lt;sequence>
		 *                   &lt;element name="IMPORTDUPS" type="{http://www.w3.org/2001/XMLSchema}string"/>
		 *                 &lt;/sequence>
		 *               &lt;/restriction>
		 *             &lt;/complexContent>
		 *           &lt;/complexType>
		 *         &lt;/element>
		 *       &lt;/sequence>
		 *     &lt;/restriction>
		 *   &lt;/complexContent>
		 * &lt;/complexType>
		 * </pre>
		 * 
		 * 
		 */
		@XmlAccessorType(XmlAccessType.FIELD)
		@XmlType(name = "", propOrder = { "staticvariables" })
		public static class DESC {

			@XmlElement(name = "STATICVARIABLES", required = true)
			protected ENVELOPE.BODY.DESC.STATICVARIABLES staticvariables;

			/**
			 * Gets the value of the staticvariables property.
			 * 
			 * @return possible object is {@link ENVELOPE.BODY.DESC.STATICVARIABLES }
			 * 
			 */
			public ENVELOPE.BODY.DESC.STATICVARIABLES getSTATICVARIABLES() {
				return staticvariables;
			}

			/**
			 * Sets the value of the staticvariables property.
			 * 
			 * @param value
			 *            allowed object is {@link ENVELOPE.BODY.DESC.STATICVARIABLES }
			 * 
			 */
			public void setSTATICVARIABLES(ENVELOPE.BODY.DESC.STATICVARIABLES value) {
				this.staticvariables = value;
			}

			/**
			 * <p>
			 * Java class for anonymous complex type.
			 * 
			 * <p>
			 * The following schema fragment specifies the expected content contained within this class.
			 * 
			 * <pre>
			 * &lt;complexType>
			 *   &lt;complexContent>
			 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
			 *       &lt;sequence>
			 *         &lt;element name="IMPORTDUPS" type="{http://www.w3.org/2001/XMLSchema}string"/>
			 *       &lt;/sequence>
			 *     &lt;/restriction>
			 *   &lt;/complexContent>
			 * &lt;/complexType>
			 * </pre>
			 * 
			 * 
			 */
			@XmlAccessorType(XmlAccessType.FIELD)
			@XmlType(name = "", propOrder = { "importdups" })
			public static class STATICVARIABLES {

				@XmlElement(name = "IMPORTDUPS", required = true)
				protected String importdups;

				/**
				 * Gets the value of the importdups property.
				 * 
				 * @return possible object is {@link String }
				 * 
				 */
				public String getIMPORTDUPS() {
					return importdups;
				}

				/**
				 * Sets the value of the importdups property.
				 * 
				 * @param value
				 *            allowed object is {@link String }
				 * 
				 */
				public void setIMPORTDUPS(String value) {
					this.importdups = value;
				}

			}

		}

	}

	/**
	 * <p>
	 * Java class for anonymous complex type.
	 * 
	 * <p>
	 * The following schema fragment specifies the expected content contained within this class.
	 * 
	 * <pre>
	 * &lt;complexType>
	 *   &lt;complexContent>
	 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	 *       &lt;sequence>
	 *         &lt;element name="VERSION" type="{http://www.w3.org/2001/XMLSchema}int"/>
	 *         &lt;element name="TALLYREQUEST" type="{http://www.w3.org/2001/XMLSchema}string"/>
	 *         &lt;element name="TYPE" type="{http://www.w3.org/2001/XMLSchema}string"/>
	 *         &lt;element name="ID" type="{http://www.w3.org/2001/XMLSchema}string"/>
	 *         &lt;element name="STATUS" type="{http://www.w3.org/2001/XMLSchema}int"/>
	 *       &lt;/sequence>
	 *     &lt;/restriction>
	 *   &lt;/complexContent>
	 * &lt;/complexType>
	 * </pre>
	 * 
	 * 
	 */
	@XmlAccessorType(XmlAccessType.FIELD)
	@XmlType(name = "", propOrder = { "version", "tallyrequest", "type", "id", "status" })
	public static class HEADER {

		@XmlElement(name = "VERSION")
		protected int version;
		@XmlElement(name = "TALLYREQUEST", required = true)
		protected String tallyrequest;
		@XmlElement(name = "TYPE", required = true)
		protected String type;
		@XmlElement(name = "ID", required = true)
		protected String id;
		@XmlElement(name = "STATUS")
		protected int status;

		/**
		 * Gets the value of the version property.
		 * 
		 */
		public int getVERSION() {
			return version;
		}

		/**
		 * Sets the value of the version property.
		 * 
		 */
		public void setVERSION(int value) {
			this.version = value;
		}

		/**
		 * Gets the value of the tallyrequest property.
		 * 
		 * @return possible object is {@link String }
		 * 
		 */
		public String getTALLYREQUEST() {
			return tallyrequest;
		}

		/**
		 * Sets the value of the tallyrequest property.
		 * 
		 * @param value
		 *            allowed object is {@link String }
		 * 
		 */
		public void setTALLYREQUEST(String value) {
			this.tallyrequest = value;
		}

		/**
		 * Gets the value of the type property.
		 * 
		 * @return possible object is {@link String }
		 * 
		 */
		public String getTYPE() {
			return type;
		}

		/**
		 * Sets the value of the type property.
		 * 
		 * @param value
		 *            allowed object is {@link String }
		 * 
		 */
		public void setTYPE(String value) {
			this.type = value;
		}

		/**
		 * Gets the value of the id property.
		 * 
		 * @return possible object is {@link String }
		 * 
		 */
		public String getID() {
			return id;
		}

		/**
		 * Sets the value of the id property.
		 * 
		 * @param value
		 *            allowed object is {@link String }
		 * 
		 */
		public void setID(String value) {
			this.id = value;
		}

		/**
		 * Gets the value of the status property.
		 * 
		 */
		public int getSTATUS() {
			return status;
		}

		/**
		 * Sets the value of the status property.
		 * 
		 */
		public void setSTATUS(int value) {
			this.status = value;
		}

	}

}
