//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.11.30 at 03:01:31 PM IST 
//


package com.punj.app.ecommerce.tally.export.voucher;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.punj.app.ecommerce.tally.export.voucher package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.punj.app.ecommerce.tally.export.voucher
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ENVELOPE }
     * 
     */
    public ENVELOPE createENVELOPE() {
        return new ENVELOPE();
    }

    /**
     * Create an instance of {@link ENVELOPE.BODY }
     * 
     */
    public ENVELOPE.BODY createENVELOPEBODY() {
        return new ENVELOPE.BODY();
    }

    /**
     * Create an instance of {@link ENVELOPE.BODY.DATA }
     * 
     */
    public ENVELOPE.BODY.DATA createENVELOPEBODYDATA() {
        return new ENVELOPE.BODY.DATA();
    }

    /**
     * Create an instance of {@link ENVELOPE.BODY.DATA.TALLYMESSAGE }
     * 
     */
    public ENVELOPE.BODY.DATA.TALLYMESSAGE createENVELOPEBODYDATATALLYMESSAGE() {
        return new ENVELOPE.BODY.DATA.TALLYMESSAGE();
    }

    /**
     * Create an instance of {@link ENVELOPE.BODY.DATA.TALLYMESSAGE.VOUCHER }
     * 
     */
    public ENVELOPE.BODY.DATA.TALLYMESSAGE.VOUCHER createENVELOPEBODYDATATALLYMESSAGEVOUCHER() {
        return new ENVELOPE.BODY.DATA.TALLYMESSAGE.VOUCHER();
    }

    /**
     * Create an instance of {@link ENVELOPE.BODY.DESC }
     * 
     */
    public ENVELOPE.BODY.DESC createENVELOPEBODYDESC() {
        return new ENVELOPE.BODY.DESC();
    }

    /**
     * Create an instance of {@link ENVELOPE.HEADER }
     * 
     */
    public ENVELOPE.HEADER createENVELOPEHEADER() {
        return new ENVELOPE.HEADER();
    }

    /**
     * Create an instance of {@link ENVELOPE.BODY.DATA.IMPORTRESULT }
     * 
     */
    public ENVELOPE.BODY.DATA.IMPORTRESULT createENVELOPEBODYDATAIMPORTRESULT() {
        return new ENVELOPE.BODY.DATA.IMPORTRESULT();
    }

    /**
     * Create an instance of {@link ENVELOPE.BODY.DATA.TALLYMESSAGE.VOUCHER.ALLLEDGERENTRIESLIST }
     * 
     */
    public ENVELOPE.BODY.DATA.TALLYMESSAGE.VOUCHER.ALLLEDGERENTRIESLIST createENVELOPEBODYDATATALLYMESSAGEVOUCHERALLLEDGERENTRIESLIST() {
        return new ENVELOPE.BODY.DATA.TALLYMESSAGE.VOUCHER.ALLLEDGERENTRIESLIST();
    }

    /**
     * Create an instance of {@link ENVELOPE.BODY.DESC.STATICVARIABLES }
     * 
     */
    public ENVELOPE.BODY.DESC.STATICVARIABLES createENVELOPEBODYDESCSTATICVARIABLES() {
        return new ENVELOPE.BODY.DESC.STATICVARIABLES();
    }

}
